apiVersion: apps/v1
kind: Deployment
metadata:
  name: gu-ml
spec:
  selector:
    matchLabels:
      app: gu-ml
  replicas: 1
  template:
    metadata:
      labels:
        app: gu-ml
    spec:
      containers:
        - name: gu-ml
          image: gu-ml:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gu-ml
spec:
  selector:
    app: gu-ml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
