apiVersion: v1
kind: Service
metadata:
  name: gu-ml-service
  labels:
    app: gu-ml
spec:
  type: NodePort # For INGRESS ClusterIP can be used as well instead of NodePort
  selector:
    app: gu-ml
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
